version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: guild_user
      POSTGRES_PASSWORD: guild_password
      POSTGRES_DB: guild_genesis
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ["/app/app"]
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      PORT: 3001
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 4321
    ports:
      - "4321:4321"
    environment:
      HOST: 0.0.0.0
      PORT: 4321
      PUBLIC_WALLET_CONNECT_PROJECT_ID: ${PUBLIC_WALLET_CONNECT_PROJECT_ID}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  pg_data:
