[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Deterministic deployments settings (see: https://getfoundry.sh/guides/deterministic-deployments-using-create2)
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  'eas-contracts/=lib/eas-contracts/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"
base-sepolia="${BASE_SEPOLIA_URL}"

[etherscan]
amoy = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }