name: Deploy Frontend to Heroku

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku Container Registry login
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_EMAIL" --password-stdin registry.heroku.com

      - name: Build and push (linux/amd64)
        env:
          HEROKU_FRONTEND_APP: ${{ secrets.HEROKU_FRONTEND_APP }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t registry.heroku.com/${HEROKU_FRONTEND_APP}/web \
            -f frontend/Dockerfile frontend \
            --push

      - name: Release on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_FRONTEND_APP: ${{ secrets.HEROKU_FRONTEND_APP }}
        run: |
          heroku container:release web -a "${HEROKU_FRONTEND_APP}"
